project_id = "xhqwmtzawqfffepcqxwf"

[functions.search-properties]
verify_jwt = false

[functions.search-openhouses] 
verify_jwt = false

[functions.manage-oauth-tokens]
verify_jwt = false

[functions.realtyna-connect]
verify_jwt = false

[functions.realtyna-callback]
verify_jwt = false

[functions.realtyna-refresh]
verify_jwt = false

[functions.sync_realtyna]
verify_jwt = false

[functions.realtyna-mls-search]
verify_jwt = false

[functions.test-realtyna-api]
verify_jwt = false

[functions.realtyna-auth-cc]
verify_jwt = false

[functions.realtyna-selftest]
verify_jwt = false

[functions.sync_members]
verify_jwt = false

[functions.sync_offices]
verify_jwt = false

[functions.sync_openhouses]
verify_jwt = false

[functions.sync_postalcodes]
verify_jwt = false

[functions.sync-orchestrator]
verify_jwt = false