project_id = "xhqwmtzawqfffepcqxwf"

[functions.search-properties]
verify_jwt = false

[functions.search-openhouses] 
verify_jwt = false

[functions.manage-oauth-tokens]
verify_jwt = false

[functions.realtyna-connect]
verify_jwt = false

[functions.realtyna-callback]
verify_jwt = false

[functions.realtyna-refresh]
verify_jwt = false